### ISSUE TITLE
qlive

### ISSUE THREAD

**Issue by AzzamDaaboul** [galacticwarrior9/Iqra#2]
Salam aleykum,

May Allah bless your work. The "-qlive" is not working". I also want to let the bot play all the time in my server. The problem is when I leave the voice channel the bot leaves it too need the bot to play Quran all the time.

Shukran wa jazakum allahu alkhaier

**Comment by galacticwarrior9** [comment]
Walaikum assalam

The bot does not currently support 24/7 playing. This is to mainly preserve bandwidth and reduce network traffic. This could change in the future, iA.
